allowBuilds:
  '@google/genai': false
  protobufjs: false
  tree-sitter-bash: false
autoInstallPeers: false
nodeLinker: hoisted
supportedArchitectures:
  os:
    - linux
    - darwin
    - win32
  cpu:
    - x64
    - arm64
    - ia32
    - arm
    - riscv64
  libc:
    - glibc
    - musl
